// flow-typed signature: 3ae58037f4b1346d8557f03404d11b59
// flow-typed version: <<STUB>>/check-node-version_v^4.0.3/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'check-node-version'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'check-node-version' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'check-node-version/bin' {
  declare module.exports: any;
}

declare module 'check-node-version/cli' {
  declare module.exports: any;
}

declare module 'check-node-version/gatekeeper' {
  declare module.exports: any;
}

declare module 'check-node-version/tools' {
  declare module.exports: any;
}

// Filename aliases
declare module 'check-node-version/bin.js' {
  declare module.exports: $Exports<'check-node-version/bin'>;
}
declare module 'check-node-version/cli.js' {
  declare module.exports: $Exports<'check-node-version/cli'>;
}
declare module 'check-node-version/gatekeeper.js' {
  declare module.exports: $Exports<'check-node-version/gatekeeper'>;
}
declare module 'check-node-version/index' {
  declare module.exports: $Exports<'check-node-version'>;
}
declare module 'check-node-version/index.js' {
  declare module.exports: $Exports<'check-node-version'>;
}
declare module 'check-node-version/tools.js' {
  declare module.exports: $Exports<'check-node-version/tools'>;
}
