// flow-typed signature: 4f4dc18edf5acc5dd5428df2381a800c
// flow-typed version: <<STUB>>/https-proxy-agent_v^5.0.0/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'https-proxy-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'https-proxy-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'https-proxy-agent/dist/agent' {
  declare module.exports: any;
}

declare module 'https-proxy-agent/dist' {
  declare module.exports: any;
}

declare module 'https-proxy-agent/dist/parse-proxy-response' {
  declare module.exports: any;
}

// Filename aliases
declare module 'https-proxy-agent/dist/agent.js' {
  declare module.exports: $Exports<'https-proxy-agent/dist/agent'>;
}
declare module 'https-proxy-agent/dist/index' {
  declare module.exports: $Exports<'https-proxy-agent/dist'>;
}
declare module 'https-proxy-agent/dist/index.js' {
  declare module.exports: $Exports<'https-proxy-agent/dist'>;
}
declare module 'https-proxy-agent/dist/parse-proxy-response.js' {
  declare module.exports: $Exports<'https-proxy-agent/dist/parse-proxy-response'>;
}
