// flow-typed signature: 0e7b68ea19e5d6803acd1fb3a68c10fc
// flow-typed version: <<STUB>>/mock-argv_v^2.0.8/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-argv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-argv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mock-argv/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mock-argv/dist/index' {
  declare module.exports: $Exports<'mock-argv/dist'>;
}
declare module 'mock-argv/dist/index.js' {
  declare module.exports: $Exports<'mock-argv/dist'>;
}
