// flow-typed signature: 8504629faeab3566273ccd8c2e819313
// flow-typed version: <<STUB>>/parse-diff_v^0.8.1/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-diff/__tests__/parse.spec' {
  declare module.exports: any;
}

declare module 'parse-diff/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-diff/__tests__/parse.spec.js' {
  declare module.exports: $Exports<'parse-diff/__tests__/parse.spec'>;
}
declare module 'parse-diff/index' {
  declare module.exports: $Exports<'parse-diff'>;
}
declare module 'parse-diff/index.js' {
  declare module.exports: $Exports<'parse-diff'>;
}
declare module 'parse-diff/parse.js' {
  declare module.exports: $Exports<'parse-diff/parse'>;
}
