// flow-typed signature: dd5132dbedcc7feffc33f6888acca7ed
// flow-typed version: <<STUB>>/zx_v4.3.0/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zx' {
  declare module.exports: any;
}
