// flow-typed signature: d6ab68aca0bf1285f22ba0af7b8b3aba
// flow-typed version: <<STUB>>/@vercel/fetch-retry_v^5.0.3/flow_v0.174.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vercel/fetch-retry'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vercel/fetch-retry' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vercel/fetch-retry/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vercel/fetch-retry/index' {
  declare module.exports: $Exports<'@vercel/fetch-retry'>;
}
declare module '@vercel/fetch-retry/index.js' {
  declare module.exports: $Exports<'@vercel/fetch-retry'>;
}
declare module '@vercel/fetch-retry/test.js' {
  declare module.exports: $Exports<'@vercel/fetch-retry/test'>;
}
